# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheus:
  metrics: true

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi