# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheus:
  metrics: true

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi